In [11]:
%pip install google_play_scraper
%pip install pyodbc
%pip install nltk

Requirement already satisfied: google_play_scraper in c:\Users\aryad\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.2.7)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pyodbc in c:\Users\aryad\AppData\Local\Programs\Python\Python311\Lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: nltk in c:\Users\aryad\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.9.4)
Requirement already satisfied: click in c:\Users\aryad\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\Users\aryad\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\aryad\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in c:\Users\aryad\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\Users\aryad\AppData\Local\Programs\Python\Python311\Lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [12]:
from google_play_scraper import Sort, reviews
app_id = "in.redbus.android"
result,continuation_token = reviews(
    app_id,
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=10000,

)

In [13]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [14]:
df_databus=pd.DataFrame(np.array(result),columns=['review'])
df_databus=df_databus.join(pd.DataFrame(df_databus.pop('review').tolist()))
df_databus.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,e0496420-d5af-4e3b-a632-ab24510a807c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sudah di coba berkali2 tetep gak bisa melakuka...,2,0,81.5.1,2026-04-25 11:43:07,"Hai Ibnu, Kami mohon maaf atas ketidaknyamanan...",2026-03-05 10:24:43,81.5.1
1,2b9a03c7-ce39-4852-9c5f-e965776ea2f8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"sayangnya tidak semua bus di tampilkan, tapi k...",2,0,81.8.5,2026-04-25 01:37:40,"Hai Kak,Kami mohon maaf atas ketidaknyamananny...",2026-04-25 19:56:30,81.8.5
2,b772cf7b-e2e3-4f8b-ac77-e22ad6097514,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi ga jelas, udah tau berurusan dengan u...",1,0,81.8.5,2026-04-24 14:07:54,"Hai Kak,Kami mohon maaf atas ketidaknyamananny...",2026-04-24 17:25:06,81.8.5
3,93105b6e-2147-4361-a0aa-6b23cbec50cf,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,oke,5,0,None,2026-04-23 15:44:31,"Hai, Terima kasih atas dukungannya! Kami senan...",2026-04-23 17:16:00,None
4,1111b4c8-1eb2-4758-8cda-c8e95e64ea20,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,mantap,5,0,81.8.5,2026-04-23 10:32:00,"Hai, Terima kasih atas dukungannya! Kami senan...",2026-04-23 17:15:50,81.8.5

In [15]:
df_databus.rename(columns={
    'content':'ReviewText',
    'score':'Rating',
    'at':'ReviewDate'
},inplace=True)
df_databus.head()

,reviewId,userName,userImage,ReviewText,Rating,thumbsUpCount,reviewCreatedVersion,ReviewDate,replyContent,repliedAt,appVersion
0,e0496420-d5af-4e3b-a632-ab24510a807c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,sudah di coba berkali2 tetep gak bisa melakuka...,2,0,81.5.1,2026-04-25 11:43:07,"Hai Ibnu, Kami mohon maaf atas ketidaknyamanan...",2026-03-05 10:24:43,81.5.1
1,2b9a03c7-ce39-4852-9c5f-e965776ea2f8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"sayangnya tidak semua bus di tampilkan, tapi k...",2,0,81.8.5,2026-04-25 01:37:40,"Hai Kak,Kami mohon maaf atas ketidaknyamananny...",2026-04-25 19:56:30,81.8.5
2,b772cf7b-e2e3-4f8b-ac77-e22ad6097514,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi ga jelas, udah tau berurusan dengan u...",1,0,81.8.5,2026-04-24 14:07:54,"Hai Kak,Kami mohon maaf atas ketidaknyamananny...",2026-04-24 17:25:06,81.8.5
3,93105b6e-2147-4361-a0aa-6b23cbec50cf,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,oke,5,0,None,2026-04-23 15:44:31,"Hai, Terima kasih atas dukungannya! Kami senan...",2026-04-23 17:16:00,None
4,1111b4c8-1eb2-4758-8cda-c8e95e64ea20,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,mantap,5,0,81.8.5,2026-04-23 10:32:00,"Hai, Terima kasih atas dukungannya! Kami senan...",2026-04-23 17:15:50,81.8.5

In [16]:
df_databus_final=df_databus[['reviewId','userName','Rating','ReviewDate','ReviewText']]
df_databus_final.head()

,reviewId,userName,Rating,ReviewDate,ReviewText
0,e0496420-d5af-4e3b-a632-ab24510a807c,Pengguna Google,2,2026-04-25 11:43:07,sudah di coba berkali2 tetep gak bisa melakuka...
1,2b9a03c7-ce39-4852-9c5f-e965776ea2f8,Pengguna Google,2,2026-04-25 01:37:40,"sayangnya tidak semua bus di tampilkan, tapi k..."
2,b772cf7b-e2e3-4f8b-ac77-e22ad6097514,Pengguna Google,1,2026-04-24 14:07:54,"Aplikasi ga jelas, udah tau berurusan dengan u..."
3,93105b6e-2147-4361-a0aa-6b23cbec50cf,Pengguna Google,5,2026-04-23 15:44:31,oke
4,1111b4c8-1eb2-4758-8cda-c8e95e64ea20,Pengguna Google,5,2026-04-23 10:32:00,mantap

In [17]:
df_databus_final.shape

(10000, 5)

In [18]:
df_databus_final_clean=df_databus_final.drop_duplicates(subset=['reviewId'])
df_databus_final_clean.shape

(10000, 5)

In [19]:
df_databus_final=df_databus[['userName','Rating','ReviewDate','ReviewText']]
df_databus_final.head()

,userName,Rating,ReviewDate,ReviewText
0,Pengguna Google,2,2026-04-25 11:43:07,sudah di coba berkali2 tetep gak bisa melakuka...
1,Pengguna Google,2,2026-04-25 01:37:40,"sayangnya tidak semua bus di tampilkan, tapi k..."
2,Pengguna Google,1,2026-04-24 14:07:54,"Aplikasi ga jelas, udah tau berurusan dengan u..."
3,Pengguna Google,5,2026-04-23 15:44:31,oke
4,Pengguna Google,5,2026-04-23 10:32:00,mantap

In [20]:
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import re

In [21]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\aryad\AppData\Roaming\nltk_data...

True

In [22]:
sia=SentimentIntensityAnalyzer()
def calculate_sentiment(review):
  review = re.sub(r'[^\w\s]', '', str(review)).lower()
  sentiment = sia.polarity_scores(str(review))
  return sentiment['compound']

def categorize_sentiment(score,rating):
    if score>0.05:
      if rating>=4:
        return 'Positive'
      elif rating == 3:
        return 'Mixed Positive'
      else:
        return 'Mixed Negative'
    elif score <-0.05:
      if rating <= 2:
        return'Negative'
      elif rating == 3:
        return 'Mixed Negative'
      else:
        return 'Mixed Positive'
    else:
      if rating >=4:
        return 'Positive'
      elif rating <=4:
        return 'Negative'
      else:
        return 'Neutral'
def sentiment_bucket(score):
  if score >= 0.5:
    return '0.5 to 1.0'
  elif 0.0 <= score <0.5:
    return '0.0 to 0.49'
  elif -0.5 <= score <0.0:
    return '-0.49 to 0.0'
  else :
    return '-1.0 to -0.5'

In [23]:
df_databus_final['SentimentScore']= df_databus_final['ReviewText'].astype(str).apply(calculate_sentiment)
df_databus_final.head()

C:\Users\aryad\AppData\Local\Temp\ipykernel_15044\3507623585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_databus_final['SentimentScore']= df_databus_final['ReviewText'].astype(str).apply(calculate_sentiment)

,userName,Rating,ReviewDate,ReviewText,SentimentScore
0,Pengguna Google,2,2026-04-25 11:43:07,sudah di coba berkali2 tetep gak bisa melakuka...,-0.250
1,Pengguna Google,2,2026-04-25 01:37:40,"sayangnya tidak semua bus di tampilkan, tapi k...",-0.128
2,Pengguna Google,1,2026-04-24 14:07:54,"Aplikasi ga jelas, udah tau berurusan dengan u...",0.000
3,Pengguna Google,5,2026-04-23 15:44:31,oke,0.000
4,Pengguna Google,5,2026-04-23 10:32:00,mantap,0.000

In [24]:
df_databus_final['SentimentCategory']=df_databus_final.apply(
    lambda row : categorize_sentiment(row['SentimentScore'], row['Rating']),
    axis=1
)
df_databus_final.head()

C:\Users\aryad\AppData\Local\Temp\ipykernel_15044\975040892.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_databus_final['SentimentCategory']=df_databus_final.apply(

,userName,Rating,ReviewDate,ReviewText,SentimentScore,SentimentCategory
0,Pengguna Google,2,2026-04-25 11:43:07,sudah di coba berkali2 tetep gak bisa melakuka...,-0.250,Negative
1,Pengguna Google,2,2026-04-25 01:37:40,"sayangnya tidak semua bus di tampilkan, tapi k...",-0.128,Negative
2,Pengguna Google,1,2026-04-24 14:07:54,"Aplikasi ga jelas, udah tau berurusan dengan u...",0.000,Negative
3,Pengguna Google,5,2026-04-23 15:44:31,oke,0.000,Positive
4,Pengguna Google,5,2026-04-23 10:32:00,mantap,0.000,Positive

In [25]:
df_databus_final['SentimentBucket']=df_databus_final['SentimentScore'].apply(sentiment_bucket)
df_databus_final.head()

C:\Users\aryad\AppData\Local\Temp\ipykernel_15044\1894946797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_databus_final['SentimentBucket']=df_databus_final['SentimentScore'].apply(sentiment_bucket)

,userName,Rating,ReviewDate,ReviewText,SentimentScore,SentimentCategory,SentimentBucket
0,Pengguna Google,2,2026-04-25 11:43:07,sudah di coba berkali2 tetep gak bisa melakuka...,-0.250,Negative,-0.49 to 0.0
1,Pengguna Google,2,2026-04-25 01:37:40,"sayangnya tidak semua bus di tampilkan, tapi k...",-0.128,Negative,-0.49 to 0.0
2,Pengguna Google,1,2026-04-24 14:07:54,"Aplikasi ga jelas, udah tau berurusan dengan u...",0.000,Negative,0.0 to 0.49
3,Pengguna Google,5,2026-04-23 15:44:31,oke,0.000,Positive,0.0 to 0.49
4,Pengguna Google,5,2026-04-23 10:32:00,mantap,0.000,Positive,0.0 to 0.49

In [26]:
jumlah_sentiment_nol=(df_databus_final["SentimentScore"]==0.0).sum()
#hitung total jumlah data
total_data=len(df_databus_final)
#hitung persentase
persentase_sentiment_nol=(jumlah_sentiment_nol/total_data)*100
#tampilkan hasil
print(f"jumlah data dengan SentimenSCore 0.0 adalah {jumlah_sentiment_nol} dari {total_data} ({persentase_sentiment_nol:.2f}%)")

jumlah data dengan SentimenSCore 0.0 adalah 7979 dari 10000 (79.79%)

In [27]:
df_databus_final2=df_databus_final[df_databus_final["SentimentScore"]!=0.0]
df_databus_final2.head(100)

,userName,Rating,ReviewDate,ReviewText,SentimentScore,SentimentCategory,SentimentBucket
0,Pengguna Google,2,2026-04-25 11:43:07,sudah di coba berkali2 tetep gak bisa melakuka...,-0.2500,Negative,-0.49 to 0.0
1,Pengguna Google,2,2026-04-25 01:37:40,"sayangnya tidak semua bus di tampilkan, tapi k...",-0.1280,Negative,-0.49 to 0.0
17,Pengguna Google,3,2026-04-19 13:00:00,apakah ini penipuan?. uang saya berkurang dr r...,-0.2960,Mixed Negative,-0.49 to 0.0
18,Pengguna Google,5,2026-04-18 18:24:32,nice apk,0.4215,Positive,0.0 to 0.49
20,Pengguna Google,2,2026-04-18 03:18:55,aplikasi yang filternya kurang Smart,0.4019,Mixed Negative,0.0 to 0.49
...,...,...,...,...,...,...,...
467,Pengguna Google,5,2026-02-16 21:13:20,good,0.4404,Positive,0.0 to 0.49
469,Pengguna Google,5,2026-02-16 15:12:00,good job,0.4404,Positive,0.0 to 0.49
474,Pengguna Google,5,2026-02-15 07:52:16,redbus is the best,0.6369,Positive,0.5 to 1.0
481,Pengguna Google,1,2026-02-13 20:12:08,beli pakai @redbus ternyata bisnya sdh tidak b...,0.5106,Mixed Negative,0.5 to 1.0
491,Pengguna Google,1,2026-02-12 12:53:35,aplikasi ga jelas mau tuker tiket PO bus Hando...,-0.8957,Negative,-1.0 to -0.5

In [28]:
df_databus_final2.shape

(2021, 7)

In [29]:
df_databus_final2.to_csv('redbus_sentiment.csv', index=False)

In [30]:
display(df_databus_final2['SentimentCategory'].value_counts())
display(df_databus_final2['SentimentCategory'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

SentimentCategory
Positive          1319
Negative           408
Mixed Negative     149
Mixed Positive     145
Name: count, dtype: int64

SentimentCategory
Positive          65.26%
Negative          20.19%
Mixed Negative     7.37%
Mixed Positive     7.17%
Name: proportion, dtype: object